DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTcwNDQ4NDg0MCwidXNlcklkIjoyfQ.OcQJJ4lvfkzaitzcLKm-zm4VkR6-1doRQrdHVyqbF1Y