DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImV4cCI6MTcwNDQ3OTcxNiwidXNlcklkIjozfQ.iQ_PKuNDlwEKxyNiQdP1m3bpyu95gOge5XxniNvmBW8